### PR TITLE
fix recipient aid references

### PR DESCRIPTION
**Pull request by lenkan**
I believe there were some missing updates from this commit: https://github.com/trustoverip/tswg-keri-specification/commit/914f6e5c23c73dca916b6e058d4ce912b048816c

### CODE REVIEW

**Comment by daidoji** [comment]
Yeah something weird happened here because I see Sam's fix on 1082 previous from that commit didn't make it either.  Also there's a typo in https://trustoverip.github.io/tswg-keri-specification/#controller-aid-field ```A Receiver AID, ~i~ri field MAY appear in other places in messages. In those cases, its meaning SHOULD be determined by the context of its appearance```

Also, I was going to push a PR but the "ri" field information is now very confusing because we have that quote with the typo saying "ri" MAY appear in that section, but then in the rest of the query messages we have that ` All are REQUIRED. No other top-level fields are allowed (MUST NOT appear)` so its unclear how that field should be used.  

I will make an issue for that one to track.

**Comment by SmithSamuelM** [comment]
Fixed with #200

**Comment by SmithSamuelM** [comment]
Fixed with #200

**Comment by daidoji** [comment]
@SmithSamuelM that fixes the issue with my particular comment and I've updated my associated issue, but I think @lenkan's other changes are still needed from this PR.  There's some ambiguity in how the `ri` field is used without the edits from his PR.

**Comment by SmithSamuelM** [comment]
I believe all the examples now include the "ri" field and the description of fields also. So I am not seeing that they are missing.

**Comment by daidoji** [comment]
@SmithSamuelM Roger on that PR.  Actually, I see where the miscommunication arises.  You're correct that `ri` does seem to exist in all the examples.  In each section though there's a list of fields like ```The top-level fields of an Exchange, exn message body MUST appear in the following order: [ v, t, d, i, x, p, dt, r, q, a]. All are REQUIRED. No other top-level fields are allowed (MUST NOT appear).```

The `ri` field is missing from all of these lists and the wording makes it seem like this field can't exist in any of those events.  See #199.

**Pull request closed without merging**
